import { collection, getDocs, query, where } from 'firebase/firestore'
import { db } from './firebase'

// 700+ Common Male Names
const MALE_NAMES: string[] = [
  'Aaron', 'Abel', 'Abraham', 'Adam', 'Adler', 'Adonis', 'Adrian', 'Aidan', 'Aiden', 'Alaric',
  'Albert', 'Alden', 'Aldo', 'Alec', 'Alejandro', 'Alex', 'Alexander', 'Alfie', 'Alfonso', 'Alfred',
  'Alonzo', 'Aloysius', 'Alvin', 'Alvis', 'Ambrose', 'Amir', 'Amos', 'Anderson', 'Andre', 'Andreas',
  'Andres', 'Andrew', 'Andy', 'Angelo', 'Angus', 'Ansel', 'Anson', 'Anthony', 'Antonio', 'Antony',
  'Apollo', 'Archer', 'Archibald', 'Archie', 'Arden', 'Ares', 'Ari', 'Arlo', 'Armand', 'Armando',
  'Arnold', 'Aron', 'Arthur', 'Arturo', 'Arvid', 'Asa', 'Asher', 'Ashton', 'Atlas', 'Atticus',
  'August', 'Augustine', 'Augustus', 'Aurelius', 'Austin', 'Axel', 'Baird', 'Baker', 'Baldwin', 'Barak',
  'Barclay', 'Barnaby', 'Barney', 'Baron', 'Barrett', 'Barry', 'Bartholomew', 'Barton', 'Basil', 'Bastian',
  'Baxter', 'Baylor', 'Beau', 'Beauregard', 'Beck', 'Beckett', 'Beckham', 'Bedford', 'Ben', 'Benedict',
  'Benjamin', 'Benji', 'Bennett', 'Bennie', 'Benny', 'Benson', 'Bentley', 'Benton', 'Berg', 'Bernard',
  'Bernardo', 'Bernie', 'Bert', 'Bertram', 'Bevis', 'Bill', 'Billy', 'Bingham', 'Birch', 'Bishop',
  'Blaine', 'Blaise', 'Blake', 'Blaze', 'Bo', 'Bob', 'Bobby', 'Bodie', 'Booker', 'Boone',
  'Boston', 'Bowen', 'Bowie', 'Boyd', 'Brad', 'Braden', 'Bradford', 'Bradley', 'Brady', 'Braeden',
  'Bram', 'Brandon', 'Brant', 'Brantley', 'Braxton', 'Brayden', 'Braylon', 'Breck', 'Brecken', 'Brendan',
  'Brenden', 'Brendon', 'Brennan', 'Brent', 'Brentley', 'Brenton', 'Brett', 'Brexton', 'Brian', 'Briar',
  'Brice', 'Bridger', 'Briggs', 'Brighton', 'Brock', 'Brodie', 'Brody', 'Bronson', 'Brooks', 'Bruce',
  'Bruno', 'Bryan', 'Bryant', 'Bryce', 'Brycen', 'Bryon', 'Brysen', 'Bryson', 'Buck', 'Bud',
  'Buddy', 'Buford', 'Burke', 'Buster', 'Byron', 'Cade', 'Caden', 'Caesar', 'Caelan', 'Cain',
  'Cal', 'Caleb', 'Callahan', 'Callum', 'Calvin', 'Camden', 'Cameron', 'Campbell', 'Camron', 'Cannon',
  'Canyon', 'Carl', 'Carlo', 'Carlos', 'Carlton', 'Carmelo', 'Carmine', 'Carson', 'Carter', 'Carver',
  'Cary', 'Casey', 'Cash', 'Cason', 'Caspar', 'Casper', 'Cassian', 'Cassius', 'Castiel', 'Cavan',
  'Cayden', 'Cecil', 'Cedric', 'Chaim', 'Channing', 'Charles', 'Charley', 'Charlie', 'Charlton', 'Chase',
  'Chauncey', 'Chester', 'Chris', 'Christian', 'Christopher', 'Chuck', 'Cian', 'Clark', 'Claude', 'Clay',
  'Clayton', 'Clement', 'Cleon', 'Cletus', 'Cleveland', 'Cliff', 'Clifford', 'Clifton', 'Clint', 'Clinton',
  'Clive', 'Clyde', 'Coby', 'Cody', 'Cohen', 'Colby', 'Cole', 'Coleman', 'Colin', 'Collin',
  'Colt', 'Colten', 'Colter', 'Colton', 'Columbus', 'Conan', 'Conner', 'Connor', 'Conor', 'Conrad',
  'Constantine', 'Cooper', 'Corban', 'Corbin', 'Corey', 'Cornelius', 'Cortez', 'Corwin', 'Cory', 'Cosimo',
  'Cosmo', 'Coty', 'Cowan', 'Craig', 'Crawford', 'Creed', 'Creighton', 'Crispin', 'Cristian', 'Crosby',
  'Cruz', 'Cullen', 'Curran', 'Curry', 'Curtis', 'Cuthbert', 'Cyrus', 'Dacian', 'Dacre', 'Dale',
  'Dallas', 'Dalton', 'Damian', 'Damien', 'Damon', 'Dan', 'Dane', 'Daniel', 'Danny', 'Dante',
  'Daren', 'Darian', 'Darin', 'Dario', 'Darius', 'Darrel', 'Darrell', 'Darren', 'Darrin', 'Darryl',
  'Darton', 'Darwin', 'Daryl', 'Dash', 'Dashel', 'Dave', 'Davenport', 'David', 'Davis', 'Davon',
  'Dawson', 'Dax', 'Daxton', 'Dayton', 'Deacon', 'Dean', 'Deandre', 'Deegan', 'Delbert', 'Delius',
  'Delmar', 'Demetrius', 'Dempsey', 'Denis', 'Dennis', 'Denny', 'Denver', 'Denzel', 'Deon', 'Derek',
  'Derick', 'Dermot', 'Derrick', 'Desmond', 'Devan', 'Devin', 'Devon', 'Devyn', 'Dexter', 'Diallo',
  'Diego', 'Dierks', 'Dieter', 'Dillon', 'Dino', 'Dion', 'Dirk', 'Dixon', 'Dmitri', 'Doane',
  'Doc', 'Domenic', 'Dominic', 'Dominick', 'Don', 'Donald', 'Donato', 'Donnie', 'Donny', 'Donovan',
  'Doran', 'Dorian', 'Doug', 'Douglas', 'Doyle', 'Drake', 'Drew', 'Duane', 'Dudley', 'Duff',
  'Duke', 'Duncan', 'Dunstan', 'Dustin', 'Dusty', 'Dwayne', 'Dwight', 'Dylan', 'Dyson', 'Earl',
  'Earnest', 'Easton', 'Eaton', 'Ed', 'Edan', 'Eddy', 'Edgar', 'Edison', 'Edmund', 'Eduardo',
  'Edward', 'Edwin', 'Egan', 'Egbert', 'Elan', 'Eland', 'Elbert', 'Elden', 'Eldon', 'Eli',
  'Elian', 'Elias', 'Eliezer', 'Elijah', 'Eliot', 'Eliseo', 'Elisha', 'Elliot', 'Elliott', 'Ellis',
  'Ellison', 'Elmer', 'Elmo', 'Elroy', 'Elton', 'Elvin', 'Elvis', 'Elwood', 'Emery', 'Emil',
  'Emiliano', 'Emilio', 'Emmet', 'Emmett', 'Emory', 'Enoch', 'Ennis', 'Enrico', 'Enrique', 'Ephraim',
  'Eric', 'Erick', 'Erland', 'Ernest', 'Ernesto', 'Ernie', 'Erno', 'Errol', 'Ervin', 'Erwin',
  'Esteban', 'Ethan', 'Etienne', 'Eugene', 'Eustace', 'Evan', 'Everett', 'Ewan', 'Ezekiel', 'Ezra',
  'Fabian', 'Fabio', 'Fairfax', 'Falcon', 'Falkner', 'Faraday', 'Farley', 'Faron', 'Farrell', 'Faust',
  'Felipe', 'Felix', 'Felton', 'Ferdinand', 'Fergus', 'Ferguson', 'Fernando', 'Ferrell', 'Fidel', 'Fielding',
  'Fife', 'Finbar', 'Findlay', 'Finley', 'Finn', 'Finnegan', 'Finnian', 'Fitch', 'Fitzgerald', 'Fitzhigh',
  'Fitzpatrick', 'Fitzroy', 'Fletcher', 'Flint', 'Florian', 'Floyd', 'Flynn', 'Foard', 'Foley', 'Forbes',
  'Ford', 'Forest', 'Forrest', 'Foster', 'Fowler', 'Fox', 'Foy', 'Francis', 'Francisco', 'Frank',
  'Frankie', 'Franklin', 'Franklyn', 'Fraser', 'Frayne', 'Fred', 'Freddie', 'Freddy', 'Frederic', 'Frederick',
  'Fredrick', 'Freeland', 'Freeman', 'Fremont', 'Fritz', 'Fulton', 'Gabriel', 'Gael', 'Gage', 'Galen',
  'Galileo', 'Gallagher', 'Galloway', 'Gamaliel', 'Gannon', 'Gardner', 'Garett', 'Garfield', 'Garland', 'Garner',
  'Garnett', 'Garold', 'Garret', 'Garrett', 'Garrick', 'Garrison', 'Garry', 'Garth', 'Garven', 'Garver',
  'Gary', 'Gaspar', 'Gaston', 'Gavin', 'Gaylord', 'Geary', 'Gene', 'General', 'Geoff', 'Geoffrey',
  'George', 'Gerald', 'Gerard', 'Gerardo', 'German', 'Gerry', 'Gibson', 'Gideon', 'Gifford', 'Gil',
  'Gilbert', 'Gilchrist', 'Giles', 'Gillespie', 'Gino', 'Giovani', 'Giovanni', 'Giuseppe', 'Glen', 'Glenn',
  'Glover', 'Glyn', 'Goddard', 'Godfrey', 'Gordon', 'Gore', 'Grady', 'Graeme', 'Graham', 'Granger',
  'Grant', 'Granville', 'Grayson', 'Green', 'Greg', 'Gregg', 'Gregory', 'Grey', 'Greyson', 'Griffin',
  'Griffith', 'Grover', 'Guido', 'Gulliver', 'Gunnar', 'Gunther', 'Gus', 'Gustaf', 'Gustav', 'Gustave',
  'Gustavus', 'Guy', 'Hadley', 'Haiden', 'Haines', 'Hakeem', 'Hal', 'Hall', 'Hallden', 'Hamilton',
  'Hamlin', 'Hammond', 'Hampton', 'Hank', 'Hans', 'Harlan', 'Harland', 'Harley', 'Harmon', 'Harold',
  'Harrell', 'Harris', 'Harrison', 'Harry', 'Hart', 'Hartford', 'Hartley', 'Harvey', 'Hasheem', 'Hassan',
  'Hayden', 'Hayes', 'Hayward', 'Hazen', 'Heath', 'Hector', 'Helias', 'Helios', 'Henderson', 'Henrik',
  'Henry', 'Herbert', 'Herman', 'Hermon', 'Hernando', 'Herschel', 'Hershel', 'Hewitt', 'Hilliard', 'Hilton',
  'Hiram', 'Hiro', 'Hobart', 'Hodge', 'Hogan', 'Holden', 'Hollis', 'Holmes', 'Homer', 'Horace',
  'Horatio', 'Horton', 'Hosea', 'Houston', 'Howard', 'Howell', 'Howie', 'Hubert', 'Hudson', 'Hugh',
  'Hughes', 'Hugo', 'Humberto', 'Humphrey', 'Hunt', 'Hunter', 'Huntington', 'Huntley', 'Hurd', 'Hurst',
  'Huxley', 'Hyatt', 'Hyland', 'Ian', 'Ibarra', 'Ibrahim', 'Ignacio', 'Ignatius', 'Ike', 'Immanuel',
  'Inigo', 'Innes', 'Ira', 'Irvin', 'Irvine', 'Irving', 'Irwin', 'Isaac', 'Isaiah', 'Isam',
  'Isiah', 'Isidore', 'Ismael', 'Israel', 'Issac', 'Ivan', 'Ives', 'Izaiah', 'Jabez', 'Jabin',
  'Jacinto', 'Jack', 'Jackson', 'Jacob', 'Jacoby', 'Jacques', 'Jaden', 'Jadon', 'Jadyn', 'Jagger',
  'Jaiden', 'Jairo', 'Jake', 'Jakob', 'Jalen', 'Jalyn', 'Jamal', 'Jamar', 'Jamarcus', 'Jameel',
  'Jamel', 'James', 'Jameson', 'Jamey', 'Jamie', 'Jamir', 'Jamison', 'Jared', 'Jarek', 'Jaren',
  'Jarod', 'Jaron', 'Jarred', 'Jarrett', 'Jarrod', 'Jarvis', 'Jasiah', 'Jason', 'Jasper', 'Javen',
  'Javier', 'Javon', 'Jax', 'Jaxon', 'Jaxson', 'Jaxton', 'Jay', 'Jayce', 'Jaycen', 'Jaycob',
  'Jayden', 'Jaydon', 'Jaylan', 'Jaylen', 'Jaylin', 'Jaylon', 'Jaymes', 'Jayson', 'Jed', 'Jedidiah',
  'Jeff', 'Jefferson', 'Jeffrey', 'Jeffry', 'Jerald', 'Jeremiah', 'Jeremy', 'Jermaine', 'Jerod', 'Jerold',
  'Jerome', 'Jeromy', 'Jerrell', 'Jerrod', 'Jerry', 'Jervis', 'Jesse', 'Jester', 'Jesus', 'Jett',
  'Jevan', 'Jim', 'Jimmie', 'Jimmy', 'Joaquin', 'Job', 'Joe', 'Joel', 'Joey', 'Johan',
  'Johannes', 'John', 'Johnathan', 'Johnathon', 'Johnny', 'Jon', 'Jonah', 'Jonas', 'Jonathan', 'Jonathon',
  'Jontae', 'Jordan', 'Jordon', 'Jordy', 'Jorge', 'Joris', 'Jose', 'Josef', 'Joseph', 'Josh',
  'Joshua', 'Josiah', 'Josue', 'Jovan', 'Jovani', 'Jovanny', 'Jovany', 'Juan', 'Judah', 'Judas',
  'Judd', 'Jude', 'Julio', 'Julius', 'Junior', 'Junius', 'Justice', 'Justin', 'Justus', 'Justyn',
  'Kade', 'Kaden', 'Kader', 'Kael', 'Kahlil', 'Kai', 'Kaiden', 'Kaine', 'Kaiser', 'Kale',
  'Kaleb', 'Kalel', 'Kalen', 'Kalvin', 'Kamden', 'Kameron', 'Kamron', 'Kane', 'Kanye', 'Karan',
  'Kareem', 'Karel', 'Karl', 'Karlo', 'Karon', 'Karson', 'Karsten', 'Karter', 'Kase', 'Kasen',
  'Kasey', 'Kash', 'Cason', 'Kayson', 'Keanu', 'Keaton', 'Kedar', 'Keegan', 'Keelan', 'Keenan',
  'Keith', 'Kellan', 'Kellen', 'Kelvin', 'Kem', 'Ken', 'Kendal', 'Kendall', 'Kendrick', 'Kenley',
  'Kennard', 'Kenneth', 'Kenney', 'Kennith', 'Kenny', 'Kent', 'Kenton', 'Kenzo', 'Keon', 'Kermit',
  'Kerr', 'Kerry', 'Kerwin', 'Keshaun', 'Keshawn', 'Kevin', 'Kevon', 'Keyon', 'Keyshawn', 'Kian',
  'Kieran', 'Killian', 'Kimball', 'Kimmel', 'King', 'Kingsley', 'Kip', 'Kiran', 'Kirby', 'Kirk',
  'Kit', 'Klaus', 'Knox', 'Kobe', 'Koby', 'Kody', 'Kolby', 'Kole', 'Kolten', 'Kolton', 'Konner',
  'Konnor', 'Kooper', 'Korey', 'Kortney', 'Kory', 'Kraig', 'Kris', 'Krishna', 'Kristian', 'Kristofer',
  'Kristopher', 'Kurt', 'Kurtis', 'Kyan', 'Kyler', 'Kyran', 'Kyree', 'Kyson', 'Lachlan', 'Laddie',
  'Lafayette', 'Laird', 'Lake', 'Lamar', 'Lamont', 'Lance', 'Landen', 'Lander', 'Lando', 'Landon',
  'Landry', 'Lane', 'Langdon', 'Langston', 'Lars', 'Larson', 'Lashawn', 'Lassen', 'Latrell', 'Laurence',
  'Lawrence', 'Lawson', 'Layne', 'Layton', 'Lazaro', 'Lazarus', 'Leander', 'Leary', 'Leaton', 'Lech',
  'Ledger', 'Lee', 'Leger', 'Leif', 'Leighton', 'Leland', 'Lemuel', 'Len', 'Lenard', 'Lennard',
  'Lennie', 'Lennon', 'Lennox', 'Lenny', 'Leo', 'Leon', 'Leonard', 'Leonardo', 'Leonel', 'Leonidas',
  'Leopold', 'Leroy', 'Les', 'Lester', 'Lev', 'Leven', 'Levi', 'Levy', 'Lew', 'Lewis',
  'Lex', 'Lexus', 'Liam', 'Lincoln', 'Linus', 'Lionel', 'Liron', 'Lloyd', 'Lochlan', 'Logan',
  'Long', 'Lonnie', 'Lonny', 'Lord', 'Loren', 'Lorenzo', 'Louie', 'Louis', 'Lovell', 'Lowell',
  'Loyd', 'Lucas', 'Lucian', 'Luciano', 'Lucien', 'Ludwig', 'Luis', 'Luke', 'Lundy', 'Lunsford',
  'Luther', 'Lyle', 'Lyman', 'Lynton', 'Lysander', 'Mac', 'Macarthur', 'Macaulay', 'Mack', 'Madan',
  'Madox', 'Maddux', 'Magnus', 'Major', 'Makai', 'Malcolm', 'Malik', 'Malone', 'Manolo', 'Manuel',
  'Marc', 'Marcel', 'Marcelo', 'Marco', 'Marcos', 'Marcus', 'Mario', 'Marion', 'Mark', 'Markus',
  'Marlin', 'Marlon', 'Marlow', 'Marlowe', 'Marquis', 'Mars', 'Marshall', 'Martin', 'Marty', 'Marvin',
  'Mason', 'Mateo', 'Mathew', 'Mathias', 'Mathieu', 'Matt', 'Matteo', 'Matthew', 'Matthias', 'Maurice',
  'Mauricio', 'Mauro', 'Maverick', 'Max', 'Maxence', 'Maxfield', 'Maxim', 'Maxime', 'Maximilian', 'Maximiliano',
  'Maximin', 'Maximus', 'Maxwell', 'Mayhew', 'Medford', 'Melvin', 'Mercer', 'Mervin', 'Mervyn',
  'Micah', 'Michael', 'Michel', 'Mick', 'Mickey', 'Midas', 'Miguel', 'Mikael', 'Mike', 'Milan',
  'Miles', 'Milford', 'Millard', 'Miller', 'Mills', 'Milo', 'Milton', 'Misha', 'Mitch', 'Mitchel',
  'Mitchell', 'Moby', 'Modesto', 'Moe', 'Mohamed', 'Mohammad', 'Mohammed', 'Moises', 'Monroe', 'Montague',
  'Monte', 'Montgomery', 'Monty', 'Mordecai', 'Morgan', 'Morris', 'Morrison', 'Mortimer', 'Morton', 'Mose',
  'Moses', 'Moss', 'Moyer', 'Murphy', 'Murray', 'Myles', 'Myron', 'Nahum', 'Nalon', 'Napoleon',
  'Nash', 'Nasir', 'Nat', 'Natan', 'Nate', 'Nathan', 'Nathaniel', 'Nathon', 'Natt', 'Naughton',
  'Navid', 'Nayan', 'Neal', 'Nealon', 'Ned', 'Nehemiah', 'Neil', 'Nelson', 'Nemo', 'Nero',
  'Nestor', 'Nethanel', 'Nevin', 'Newell', 'Newman', 'Newton', 'Niall', 'Niblett', 'Nic', 'Nicholas',
  'Nicholaus', 'Nick', 'Nickolas', 'Nicky', 'Nico', 'Nicolas', 'Nikko', 'Niko', 'Nikolai', 'Nikolas',
  'Niles', 'Nils', 'Ninian', 'Niven', 'Nixon', 'Noah', 'Noble', 'Noel', 'Nolan', 'Norbert',
  'Norm', 'Norman', 'Normand', 'Norris', 'Norton', 'Norwood', 'Novak', 'Nye', 'Nyle', 'Yadiel',
  'Yago', 'Yahir', 'Yancey', 'Yanis', 'Yared', 'Yaromir', 'Yasir', 'Yates', 'Yeardley', 'Yehudi',
  'Yonin', 'Yorick', 'York', 'Yosef', 'Yoshio', 'Young', 'Yul', 'Yule', 'Yusef', 'Yusuf',
  'Yvain', 'Yves', 'Yvon', 'Zac', 'Zach', 'Zachariah', 'Zachary', 'Zachery', 'Zack', 'Zackary',
  'Zackery', 'Zade', 'Zadok', 'Zhid', 'Zahir', 'Zaid', 'Zain', 'Zaine', 'Zak', 'Zakaria',
  'Zakariya', 'Zaki', 'Zakir', 'Zale', 'Zalman', 'Zander', 'Zane', 'Zani', 'Zareb', 'Zared',
  'Zarley', 'Zavier', 'Zayd', 'Zayden', 'Zayne', 'Zeb', 'Zebadiah', 'Zebedee', 'Zebulon', 'Zebulun',
  'Zed', 'Zedekiah', 'Zef', 'Zeke', 'Zelig', 'Zenas', 'Zene', 'Zenon', 'Zenos', 'Zephan',
  'Zephaniah', 'Zephyr', 'Zephyrus', 'Zeshawn', 'Zev', 'Zian', 'Ziad', 'Ziben', 'Ziggy', 'Zildjian',
  'Zimri', 'Zion', 'Ziv', 'Ziven', 'Ziyaad', 'Ziyad', 'Zoltan', 'Zoran', 'Zosimo', 'Zosimus',
  'Zuba', 'Zuberi', 'Zuhair', 'Zwi', 'Zygmunt'
]

// 700+ Common Female Names
const FEMALE_NAMES: string[] = [
  'Abby', 'Abigail', 'Ada', 'Adah', 'Adalyn', 'Addison', 'Adela', 'Adelaide', 'Adele', 'Adeline',
  'Adiel', 'Adriana', 'Adrienne', 'Afton', 'Agatha', 'Agnes', 'Aiko', 'Aileen', 'Ailsa', 'Aimee',
  'Ainsley', 'Alaina', 'Alana', 'Alberta', 'Alecia', 'Alena', 'Alesha', 'Alexa', 'Alexandra', 'Alexia',
  'Alexis', 'Alicia', 'Alina', 'Alisa', 'Alisha', 'Alison', 'Alissa', 'Allie', 'Allison', 'Alma',
  'Alondra', 'Althea', 'Alyson', 'Alyssa', 'Amara', 'Amari', 'Amaya', 'Amber', 'Amelia', 'Amelie',
  'Amethyst', 'Amira', 'Amity', 'Amy', 'Anabel', 'Anastasia', 'Andrea', 'Andromeda', 'Angel', 'Angela',
  'Angelica', 'Angelina', 'Angeline', 'Anika', 'Anita', 'Aniya', 'Ann', 'Anna', 'Annabel', 'Annabella',
  'Annabelle', 'Annalise', 'Anne', 'Annette', 'Annie', 'Antoinette', 'Antonia', 'Apple', 'April', 'Arabella',
  'Aria', 'Ariadne', 'Ariana', 'Arianna', 'Ariel', 'Ariella', 'Arielle', 'Arya', 'Ashley', 'Ashlyn',
  'Aspen', 'Astrid', 'Athena', 'Aubree', 'Aubrey', 'Audrey', 'Audrina', 'Augusta', 'Aurelia', 'Aurora',
  'Austen', 'Autumn', 'Ava', 'Avalon', 'Avery', 'Ayla', 'Aylin', 'Azalea', 'Azariah', 'Baby',
  'Bailey', 'Barbara', 'Beata', 'Beatrice', 'Beatrix', 'Becca', 'Bela', 'Belinda', 'Bell', 'Bella',
  'Bellamy', 'Belle', 'Berenice', 'Bernice', 'Berta', 'Bertha', 'Beryl', 'Bess', 'Bessie', 'Beth',
  'Bethany', 'Betsy', 'Bette', 'Bettina', 'Betty', 'Bexley', 'Bianca', 'Billie', 'Blanche', 'Blakely',
  'Bobbi', 'Bonita', 'Bonnie', 'Braelyn', 'Brandy', 'Breanna', 'Bree', 'Breeze', 'Brenda', 'Brenna',
  'Briana', 'Brianna', 'Brielle', 'Briella', 'Bristol', 'Britney', 'Brittany', 'Britton', 'Bronte', 'Brooke',
  'Brooklyn', 'Brynn', 'Cadence', 'Caitlin', 'Caitlyn', 'Calista', 'Callie', 'Camila', 'Camilla', 'Camille',
  'Candace', 'Candice', 'Candy', 'Capri', 'Cara', 'Carina', 'Carla', 'Carlene', 'Carly', 'Carmela',
  'Carmen', 'Carol', 'Carole', 'Carolina', 'Caroline', 'Carolyn', 'Carrie', 'Cassandra', 'Cassia', 'Cassie',
  'Catalina', 'Catarina', 'Catherine', 'Cathleen', 'Cathy', 'Catrina', 'Cayla', 'Cece', 'Cecilia',
  'Cecily', 'Celeste', 'Celia', 'Celina', 'Celine', 'Charity', 'Charlene', 'Charlotte', 'Charmaine', 'Chasity',
  'Chaya', 'Chelsea', 'Cherie', 'Cherish', 'Cherry', 'Cheryl', 'Chesney', 'Cheyenne', 'Chiara', 'Chloe',
  'Christiana', 'Christina', 'Christine', 'Christy', 'Ciara', 'Cicely', 'Ciel', 'Cinderella', 'Cindy', 'Claire',
  'Clara', 'Clare', 'Clarissa', 'Claudia', 'Clementine', 'Cleo', 'Cloe', 'Clover', 'Coco', 'Colette',
  'Colleen', 'Collins', 'Constance', 'Consuelo', 'Cora', 'Coral', 'Coralie', 'Cordelia', 'Corinne', 'Courtney',
  'Cove', 'Crystal', 'Cynthia', 'Cyprian', 'Daisy', 'Dakota', 'Dana', 'Daphne', 'Dara', 'Darcy',
  'Daria', 'Darla', 'Darleen', 'Darlene', 'Davina', 'Dawn', 'Deanna', 'Debby', 'Deborah', 'Debra',
  'Dee', 'Deidre', 'Deirdre', 'Delaney', 'Delfina', 'Delia', 'Delilah', 'Dell', 'Della', 'Delores',
  'Delphine', 'Demetria', 'Demi', 'Desirae', 'Desiree', 'Destinee', 'Destiny', 'Diana', 'Diane',
  'Dianna', 'Dianne', 'Dixie', 'Dolly', 'Dolores', 'Dominique', 'Donna', 'Dora', 'Dorcas', 'Doreen',
  'Doris', 'Dorothea', 'Dorothy', 'Dory', 'Drew', 'Earlene', 'Ebony', 'Echo', 'Eden', 'Edie',
  'Edith', 'Edna', 'Edwina', 'Effie', 'Eileen', 'Eirene', 'Elaine', 'Elda', 'Eleanor', 'Electra',
  'Elena', 'Eleni', 'Eliana', 'Elin', 'Elina', 'Elisa', 'Elisabeth', 'Elise', 'Elissa', 'Eliza',
  'Elizabeth', 'Ella', 'Elle', 'Ellen', 'Ellery', 'Ellie', 'Ellison', 'Elma', 'Elodie', 'Eloise',
  'Elsa', 'Elsie', 'Elvira', 'Elyse', 'Ember', 'Emely', 'Emera', 'Emerald', 'Emilia', 'Emilie',
  'Emily', 'Emma', 'Emmeline', 'Emmerson', 'Emmie', 'Emmy', 'Ena', 'Enid', 'Epiphany', 'Erica',
  'Erika', 'Erin', 'Iris', 'Erma', 'Esme', 'Esmeralda', 'Esperanza', 'Estela', 'Estelle', 'Ester',
  'Esther', 'Estrella', 'Ethel', 'Ethelyn', 'Etta', 'Eudora', 'Eugenia', 'Eulalia', 'Eunice', 'Eva',
  'Evangeline', 'Eve', 'Evelyn', 'Everley', 'Everly', 'Evie', 'Evita', 'Faith', 'Fancy', 'Fanny',
  'Farrah', 'Fawn', 'Fay', 'Faye', 'Felicia', 'Felicity', 'Fern', 'Fernanda', 'Fidelia', 'Fiona',
  'Flavia', 'Fleur', 'Flora', 'Florence', 'Florrie', 'Flossie', 'Flower', 'Fontayne', 'Fran', 'Frances',
  'Francesca', 'Francisca', 'Freda', 'Freya', 'Frida', 'Frieda', 'Fulvia', 'Gabriela', 'Gabriella',
  'Gabrielle', 'Gaby', 'Gaia', 'Gail', 'Gale', 'Gemma', 'Genesis', 'Geneva', 'Genevieve', 'Georgette',
  'Georgia', 'Georgina', 'Gia', 'Gianna', 'Gillian', 'Gina', 'Ginger', 'Giovanna', 'Gisela', 'Gisele',
  'Giselle', 'Gladys', 'Glenda', 'Glenna', 'Gloria', 'Golda', 'Goldie', 'Grace', 'Gracelyn', 'Gracia',
  'Gracie', 'Greta', 'Gretchen', 'Gretel', 'Griselda', 'Guadalupe', 'Guinevere', 'Gwen', 'Gwendolyn', 'Gwyneth',
  'Hadassah', 'Hailee', 'Hailey', 'Hailie', 'Halle', 'Hallie', 'Halsey', 'Hana', 'Hanna', 'Hannah',
  'Harmony', 'Harper', 'Harriet', 'Hattie', 'Haven', 'Haylee', 'Hayley', 'Hazel', 'Heather', 'Hedy',
  'Heidi', 'Helen', 'Helena', 'Helene', 'Helga', 'Hellen', 'Henrietta', 'Hermione', 'Hester', 'Hettie',
  'Hillary', 'Hilary', 'Hilda', 'Hildegard', 'Holly', 'Honey', 'Hope', 'Hulda', 'Ianthe', 'Ica',
  'Ida', 'Idabelle', 'Idalia', 'Idelle', 'Ila', 'Ilene', 'Iliana', 'Illa', 'Ilona', 'Ilse',
  'Imani', 'Imogene', 'Ina', 'India', 'Indigo', 'Ines', 'Inez', 'Inga', 'Ingrid', 'Iola',
  'Iona', 'Irena', 'Irene', 'Isa', 'Isabel', 'Isabella', 'Isabelle', 'Isadora', 'Isis', 'Isla',
  'Ita', 'Itzel', 'Iva', 'Ivah', 'Ivana', 'Ivanna', 'Ivette', 'Ivy', 'Jacqueline', 'Jacquelyn',
  'Jada', 'Jade', 'Jaelynn', 'Jaida', 'Jaida', 'Jamiya', 'Jan', 'Jana', 'Janae', 'Janelle',
  'Janet', 'Janette', 'Janice', 'Janie', 'Janine', 'Janis', 'Jasmine', 'Jayla', 'Jayla', 'Jaycee',
  'Jayla', 'Jaylee', 'Jayleen', 'Jaylin', 'Jayme', 'Jean', 'Jeanette', 'Jeanie', 'Jeanne', 'Jeannette',
  'Jeannie', 'Jemima', 'Jenifer', 'Jenna', 'Jenni', 'Jennie', 'Jennifer', 'Jenny', 'Jeri', 'Jersey',
  'Jessica', 'Jessie', 'Jewel', 'Jewell', 'Jillian', 'Jo', 'Joan', 'Joann', 'Joanna', 'Joanne',
  'Jocelyn', 'Jodi', 'Jodie', 'Jody', 'Joelle', 'Johana', 'Johanna', 'Jolene', 'Jolie', 'Joni',
  'Jordyn', 'Josefa', 'Josefina', 'Josephine', 'Josie', 'Joslyn', 'Joy', 'Joyce', 'Juana',
  'Juanita', 'Judith', 'Judy', 'Julia', 'Juliana', 'Julianna', 'Julianne', 'Julie', 'Juliet', 'Juliette',
  'Julissa', 'June', 'Justine', 'Kaelyn', 'Kaia', 'Kailyn', 'Kaitlin', 'Kaitlyn', 'Kaleigh', 'Kaley',
  'Kali', 'Kallie', 'Kamila', 'Kamille', 'Kamryn', 'Kanisha', 'Kara', 'Karen', 'Kari', 'Karin',
  'Karina', 'Karla', 'Karlee', 'Karley', 'Karli', 'Karlie', 'Karol', 'Karolina', 'Karoline', 'Kary',
  'Karyn', 'Kasey', 'Kassandra', 'Kassidy', 'Kate', 'Katelyn', 'Katelynn', 'Katerina', 'Katharine', 'Katherine',
  'Kathleen', 'Kathryn', 'Kathy', 'Katie', 'Katina', 'Katlyn', 'Katrina', 'Katty', 'Kay', 'Kaydence',
  'Kaye', 'Kayla', 'Kaylah', 'Kaylee', 'Kayleen', 'Kayleigh', 'Kaylen', 'Kayley', 'Kayli', 'Kaylie',
  'Kaylin', 'Kaylyn', 'Kaylynn', 'Keira', 'Keely', 'Kelli', 'Kellie', 'Kelly', 'Kelsey', 'Kelsie',
  'Kenna', 'Kennedy', 'Kenza', 'Kerry', 'Kiana', 'Kianna', 'Kiara', 'Kiera', 'Kiersten', 'Kiki',
  'Kiley', 'Kim', 'Kimber', 'Kimberlee', 'Kimberley', 'Kimberly', 'Kira', 'Kirsten', 'Kirsty', 'Kitty',
  'Kora', 'Kori', 'Kortney', 'Krista', 'Kristen', 'Kristi', 'Kristie', 'Kristin', 'Kristina', 'Kristine',
  'Kristy', 'Krystal', 'Kyla', 'Kylee', 'Kyleigh', 'Kylie', 'Kym', 'Kyra', 'Lacey', 'Lacy',
  'Laia', 'Laila', 'Lainey', 'Laken', 'Lana', 'Laney', 'Lani', 'Lara', 'Larissa', 'Lark',
  'Latasha', 'Laura', 'Laurel', 'Lauren', 'Laurie', 'Lauryn', 'Lavender', 'Laverne', 'Lavina', 'Lavinia',
  'Layla', 'Lea', 'Leah', 'Leandra', 'Leann', 'Leanna', 'Leanne', 'Leda', 'Leela', 'Leena',
  'Leesa', 'Leia', 'Leigh', 'Leila', 'Leilani', 'Lena', 'Lenore', 'Leona', 'Leonor', 'Leonora',
  'Lesley', 'Leslie', 'Lesly', 'Letitia', 'Lettie', 'Lexi', 'Lexie', 'Lexis', 'Leyla', 'Liana',
  'Libby', 'Liberty', 'Lida', 'Lidia', 'Liesel', 'Lila', 'Lilah', 'Lilian', 'Liliana', 'Lilianna',
  'Lilith', 'Lilias', 'Lilla', 'Lillian', 'Lillie', 'Lilly', 'Lily', 'Lilyana', 'Lina', 'Linda',
  'Lindsay', 'Lindsey', 'Lindy', 'Lisa', 'Lisandra', 'Lisette', 'Lissa', 'Lita', 'Liv', 'Livia',
  'Livvy', 'Liz', 'Liza', 'Lizabeth', 'Lizbet', 'Lizbeth', 'Lizette', 'Lizzie', 'Lizzy', 'Lola',
  'London', 'Lois', 'Lora', 'Loran', 'Lorelai', 'Lorelei', 'Loren', 'Lorena', 'Loretta', 'Lori',
  'Lorie', 'Loris', 'Lorna', 'Lorraine', 'Lottie', 'Lou', 'Louisa', 'Louise', 'Lourdes', 'Love',
  'Lucia', 'Luciana', 'Lucianne', 'Lucile', 'Lucilla', 'Lucille', 'Lucinda', 'Lucy', 'Luella', 'Luisa',
  'Lula', 'Lulu', 'Luna', 'Luz', 'Lydia', 'Lyla', 'Lynda', 'Lyndsay', 'Lyndsey', 'Lynette',
  'Lynn', 'Lynne', 'Lyra', 'Lyric', 'Mabel', 'Mable', 'Macey', 'Macie', 'Mackenzie', 'Macy',
  'Maddie', 'Maddy', 'Madeline', 'Madelyn', 'Madelynn', 'Madge', 'Madison', 'Madisyn', 'Madonna', 'Mae',
  'Maegan', 'Maeve', 'Maggie', 'Magnolia', 'Maia', 'Maisie', 'Makayla', 'Makena', 'Makenna', 'Makenzie',
  'Maleah', 'Malia', 'Mallory', 'Manuela', 'Mara', 'Marcela', 'Marcelina', 'Marci', 'Marcia', 'Marcie',
  'Marcy', 'Margaret', 'Margarita', 'Marge', 'Margery', 'Margie', 'Margo', 'Margot', 'Marguerite', 'Maria',
  'Mariah', 'Mariam', 'Marian', 'Mariana', 'Marianna', 'Marianne', 'Maribel', 'Marie', 'Mariela', 'Mariella',
  'Marielle', 'Marilyn', 'Marina', 'Marisa', 'Marisol', 'Marissa', 'Maritza', 'Marjorie', 'Marla', 'Marlee',
  'Marlena', 'Marlene', 'Marley', 'Marni', 'Marnie', 'Marquita', 'Marsha', 'Marta', 'Martha', 'Martina',
  'Mary', 'Maryann', 'Marybeth', 'Maryjane', 'Marylou', 'Maryse', 'Matilda', 'Matilde', 'Mattie', 'Maud',
  'Maude', 'Maura', 'Maureen', 'Mavis', 'Maxine', 'May', 'Maya', 'Mayra', 'Meadow', 'Meagan',
  'Meaghan', 'Meera', 'Meg', 'Megan', 'Meghan', 'Melanie', 'Melina', 'Melinda', 'Melisande', 'Melissa',
  'Melody', 'Melva', 'Melvina', 'Mendy', 'Mercedes', 'Mercy', 'Meredith', 'Mia', 'Micaela', 'Michaela',
  'Michal', 'Michele', 'Michelle', 'Mika', 'Mikaela', 'Mikayla', 'Mila', 'Milagros', 'Milena', 'Miley',
  'Millicent', 'Millie', 'Mimi', 'Mina', 'Mindy', 'Minerva', 'Minnie', 'Mira', 'Mirabelle', 'Miracle',
  'Miranda', 'Miriam', 'Misty', 'Miya', 'Modesta', 'Moira', 'Mollie', 'Molly', 'Mona', 'Monique',
  'Montana', 'Morgan', 'Moriah', 'Mulan', 'Muriel', 'Myra', 'Myrna', 'Myrtle', 'Nadia', 'Nadine',
  'Nala', 'Nan', 'Nana', 'Nance', 'Nanci', 'Nancy', 'Nanette', 'Nanny', 'Naomi', 'Nara',
  'Narcissa', 'Natalia', 'Natalie', 'Nataly', 'Natasha', 'Nathalie', 'Nathalie', 'Neva', 'Nevada', 'Nevaeh',
  'Neve', 'Nia', 'Kiana', 'Kianna', 'Kiara', 'Kiera', 'Kiki', 'Kiley', 'Kim', 'Kimber',
  'Kimberlee', 'Kimberley', 'Kimberly', 'Kira', 'Kirsten', 'Kirsty', 'Kitty', 'Kora', 'Kori',
  'Kortney', 'Krista', 'Kristen', 'Kristi', 'Kristie', 'Kristin', 'Kristina', 'Kristine', 'Kristy',
  'Krystal', 'Kyla', 'Kylee', 'Kyleigh', 'Kylie', 'Kym', 'Kyra', 'Nelia', 'Nell',
  'Nellie', 'Nelly', 'Nena', 'Neola', 'Nera', 'Neri', 'Nessa', 'Nettie', 'Neva', 'Nia',
  'Nichole', 'Nicola', 'Nicole', 'Nicolette', 'Nida', 'Nika', 'Nike', 'Nikita', 'Niki', 'Nikki',
  'Nila', 'Nina', 'Nisa', 'Nisha', 'Nita', 'Noa', 'Noelia', 'Noelle', 'Noemi', 'Nola',
  'Nona', 'Nora', 'Norah', 'Noreen', 'Nori', 'Norma', 'Nova', 'Nydia', 'Nyla', 'Nylah',
  'Nyra', 'Oceana', 'Octavia', 'Oda', 'Odele', 'Odelia', 'Odessa', 'Odetta', 'Odette', 'Ofelia',
  'Ola', 'Olga', 'Oliva', 'Olive', 'Olivia', 'Olla', 'Ollie', 'Oma', 'Ona', 'Ondine',
  'Oona', 'Opal', 'Ophelia', 'Oriana', 'Oriel', 'Orla', 'Orlean', 'Ofelia', 'Paige', 'Paloma',
  'Pam', 'Pamela', 'Pamelia', 'Pandi', 'Pandora', 'Pansy', 'Paola', 'Paris', 'Patricia', 'Patsy',
  'Patty', 'Paula', 'Paulette', 'Paulina', 'Pauline', 'Paz', 'Peach', 'Pearl', 'Pearle', 'Peggy',
  'Penelope', 'Penney', 'Pennie', 'Penny', 'Pepper', 'Perdita', 'Petra', 'Petula', 'Phaedra', 'Phebe',
  'Philippa', 'Phillipa', 'Philomena', 'Phoebe', 'Piper', 'Pippa', 'Polly', 'Poppy', 'Portia', 'Posey',
  'Prudence', 'Prue', 'Rachel', 'Rachelle', 'Rae', 'Raegan', 'Raelynn', 'Rafaela', 'Raina', 'Raine',
  'Ramona', 'Raquel', 'Raven', 'Raya', 'Rayna', 'Rea', 'Reanna', 'Reba', 'Rebecca', 'Rebekah',
  'Regan', 'Regina', 'Reina', 'Remi', 'Rena', 'Renata', 'Renate', 'Rene', 'Renee', 'Rennie',
  'Rhea', 'Rhianna', 'Rhiannon', 'Rhoda', 'Rhonda', 'Rhyan', 'Ria', 'Richelle', 'Ricki', 'Rickie',
  'Riley', 'Rilla', 'Risa', 'Rita', 'River', 'Rivka', 'Roberta', 'Robin', 'Robyn', 'Rocio',
  'Romy', 'Ronda', 'Roni', 'Ronnie', 'Ronny', 'Rosa', 'Rosabel', 'Rosalee', 'Rosalie', 'Rosalind',
  'Rosalinda', 'Rosalyn', 'Rosamond', 'Rosanna', 'Rosanne', 'Rosario', 'Rose', 'Roseanne', 'Roseline',
  'Roselyn', 'Rosemarie', 'Rosemary', 'Rosetta', 'Rosie', 'Rosina', 'Roslyn', 'Rowena', 'Roxana',
  'Roxanne', 'Roxie', 'Ruby', 'Rue', 'Ruth', 'Ruthie', 'Ryann', 'Rye', 'Rylee', 'Ryleigh',
  'Rylie', 'Sabina', 'Sabine', 'Sabra', 'Sabrina', 'Sacha', 'Sadie', 'Sage', 'Salina', 'Sally',
  'Samantha', 'Samara', 'Sammy', 'Samyia', 'Sandra', 'Sandy', 'Sara', 'Sarah', 'Sarahi', 'Sari',
  'Sasha', 'Savanna', 'Savannah', 'Saylor', 'Scarlet', 'Scarlett', 'Selah', 'Selena', 'Selene',
  'Selina', 'Selma', 'Seraphina', 'Seraphine', 'Serena', 'Serenity', 'Shae', 'Shana', 'Shani',
  'Shania', 'Shanice', 'Shanna', 'Shannon', 'Shantel', 'Shari', 'Sharon', 'Sharyl', 'Shasta', 'Shauna',
  'Shawna', 'Shay', 'Shayla', 'Shayna', 'Shea', 'Sheena', 'Sheila', 'Shelby', 'Shelia', 'Shelley',
  'Shelly', 'Sheridan', 'Sherri', 'Sherrie', 'Sherrill', 'Sherry', 'Shila', 'Shilah', 'Shilo', 'Shiloh',
  'Shirley', 'Shyann', 'Shyla', 'Sian', 'Sibyl', 'Sienna', 'Siena', 'Sierra', 'Signe', 'Sigrid',
  'Silvana', 'Silvia', 'Sima', 'Simona', 'Simone', 'Siri', 'Sissy', 'Skye', 'Skyla', 'Skylar',
  'Skyler', 'Sloan', 'Sloane', 'Snow', 'Sofia', 'Sofie', 'Sondra', 'Sonia', 'Sonja', 'Sonya',
  'Sophia', 'Sophie', 'Sophy', 'Spring', 'Stacey', 'Stacy', 'Star', 'Starr', 'Stefanie', 'Stella',
  'Stephanie', 'Stevie', 'Sue', 'Suki', 'Sunny', 'Sunshine', 'Susan', 'Susana', 'Susanna', 'Susannah',
  'Susanne', 'Susie', 'Suzanna', 'Suzanne', 'Suzette', 'Suzi', 'Suzie', 'Suzy', 'Sybil', 'Sydnee',
  'Sydney', 'Sydni', 'Sydnie', 'Sylva', 'Sylvia', 'Sylvie', 'Symone', 'Tabitha', 'Tacy', 'Talia',
  'Talitha', 'Tallulah', 'Tama', 'Tamara', 'Tameka', 'Tami', 'Tamia', 'Tamika', 'Tammi', 'Tammie',
  'Tammy', 'Tamra', 'Tanya', 'Tara', 'Tasha', 'Tashia', 'Tatiana', 'Tatum', 'Tatyana', 'Tawny',
  'Taya', 'Tayla', 'Tayler', 'Taylor', 'Teagan', 'Teegan', 'Tegan', 'Telma', 'Temperance', 'Temple',
  'Teresa', 'Teri', 'Terri', 'Terrie', 'Terry', 'Tess', 'Tessa', 'Thalia', 'Thea', 'Thelma',
  'Theodora', 'Theodosia', 'Theresa', 'Therese', 'Tia', 'Tiara', 'Tiana', 'Tianna', 'Tiera', 'Tierney',
  'Tiffany', 'Tilda', 'Tillie', 'Tilly', 'Tina', 'Tinsley', 'Tobie', 'Toni', 'Tonia', 'Tonya',
  'Tori', 'Torrie', 'Tory', 'Tove', 'Tracey', 'Traci', 'Tracie', 'Tracy', 'Tricia', 'Trina',
  'Trinity', 'Trish', 'Trisha', 'Trudy', 'Tyra', 'Una', 'Unity', 'Ursula', 'Valarie', 'Valentina',
  'Valeria', 'Valerie', 'Valery', 'Valor', 'Vanessa', 'Veda', 'Velia', 'Velma', 'Vera', 'Verd',
  'Verdell', 'Veronica', 'Vesta', 'Vickey', 'Vicki', 'Vickie', 'Vicky', 'Victoria', 'Victorina', 'Vida',
  'Viola', 'Violet', 'Violetta', 'Vira', 'Virginia', 'Vivian', 'Viviana', 'Vivienne', 'Vonda', 'Willa',
  'Wilma', 'Winifred', 'Winnie', 'Winnifred', 'Winona', 'Wren', 'Wynne', 'Wynter', 'Xandra', 'Xanthe',
  'Xanthia', 'Xaviera', 'Xena', 'Xenia', 'Xiomara', 'Yael', 'Yareli', 'Yaretzi', 'Yaris', 'Yasmin',
  'Yasmine', 'Yolanda', 'Yvette', 'Yvonne', 'Zada', 'Zadie', 'Zahra', 'Zaida', 'Zaidee', 'Zaira',
  'Zandra', 'Zara', 'Zarah', 'Zaria', 'Zariah', 'Zea', 'Zelene', 'Zelia', 'Zelma', 'Zena',
  'Zene', 'Zenia', 'Zenobia', 'Zephyr', 'Zia', 'Zianna', 'Zillah', 'Zilpah', 'Zina', 'Ziona',
  'Zippora', 'Zipporah', 'Zita', 'Ziv', 'Ziva', 'Zoe', 'Zoey', 'Zofia', 'Zoie', 'Zola',
  'Zona', 'Zora', 'Zorabelle', 'Zorah', 'Zorina', 'Zowie', 'Zula', 'Zuri', 'Zuzanna', 'Zyta'
]

// Unisex / General Names
const UNISEX_NAMES: string[] = [
  'Alex', 'Alexis', 'Amari', 'Ariel', 'Arrow', 'Ash', 'Ashton', 'Aspen', 'Aubrey', 'Avery',
  'Bailey', 'Bay', 'Blair', 'Blake', 'Bowie', 'Briar', 'Brooklyn', 'Cameron', 'Campbell', 'Canyon',
  'Casey', 'Charley', 'Charlie', 'Chris', 'Cody', 'Dakota', 'Dallas', 'Darcy', 'Devon', 'Dylan',
  'Eden', 'Elliot', 'Ellis', 'Emerson', 'Emery', 'Finley', 'Flynn', 'Forest', 'Gale', 'Gray',
  'Greer', 'Grey', 'Harley', 'Harper', 'Haven', 'Hayden', 'Indigo', 'Jade', 'Jamie', 'Jayden',
  'Jordan', 'Jules', 'Justice', 'Kai', 'Kelly', 'Kendall', 'Kennedy', 'Kerry', 'Kim', 'Kit',
  'Lane', 'Lee', 'Lennon', 'Logan', 'Marley', 'Max', 'Mickey', 'Morgan', 'Murphy', 'Nova',
  'Oakley', 'Ocean', 'Ollie', 'Parker', 'Peyton', 'Phoenix', 'Quinn', 'Reagan', 'Reece', 'Reed',
  'Reese', 'Remy', 'Riley', 'River', 'Rory', 'Rowan', 'Ryan', 'Ryder', 'Sage', 'Sam',
  'Sawyer', 'Scout', 'Shay', 'Shiloh', 'Skyler', 'Sloan', 'Storm', 'Sunny', 'Sutton', 'Sydney',
  'Taylor', 'Toby', 'Toni', 'Tory', 'Val', 'Vance', 'West', 'Winter', 'Wyatt', 'Wynn'
]

/**
 * Returns a random English name based on selected gender
 */
export function getRandomEnglishName(gender?: 'male' | 'female' | 'unisex'): string {
  let list = UNISEX_NAMES
  if (gender === 'male') {
    list = MALE_NAMES
  } else if (gender === 'female') {
    list = FEMALE_NAMES
  } else {
    // Merge all lists for unisex/any
    list = [...MALE_NAMES, ...FEMALE_NAMES, ...UNISEX_NAMES]
  }

  const randomIndex = Math.floor(Math.random() * list.length)
  return list[randomIndex]
}

/**
 * Generates a unique English name by picking random names and verifying against existing Firestore records.
 * Keeps looking until it finds one that is not in use.
 */
export async function generateUniqueEnglishName(gender?: 'male' | 'female' | 'unisex'): Promise<string> {
  const maxAttempts = 100
  let attempts = 0

  while (attempts < maxAttempts) {
    const candidate = getRandomEnglishName(gender)

    // 1. Check in students collection
    const studentSnap = await getDocs(query(collection(db, 'students'), where('code', '==', candidate)))
    if (!studentSnap.empty) {
      attempts++
      continue
    }

    // 2. Check in teachers collection
    const teacherSnap = await getDocs(query(collection(db, 'teachers'), where('code', '==', candidate)))
    if (!teacherSnap.empty) {
      attempts++
      continue
    }

    return candidate
  }

  // Fallback if somehow there's a collision on all attempts (e.g. 100 attempts all hit existing names)
  // Append a small random 2-digit number
  const candidate = getRandomEnglishName(gender)
  const randomSuffix = Math.floor(10 + Math.random() * 90)
  return `${candidate}${randomSuffix}`
}
