import { create } from 'zustand'
import { persist } from 'zustand/middleware'

type Lang = 'vi' | 'en'

interface LangState {
  lang: Lang
  setLang: (lang: Lang) => void
  t: (key: string) => string
}

const translations: Record<string, Record<Lang, string>> = {
  // TeacherLayout
  'nav.attendance': { vi: 'Điểm danh', en: 'Attendance' },
  'nav.makeup_attendance': { vi: 'Điểm danh bù', en: 'Make-up attendance' },
  'nav.ranking': { vi: 'Xếp hạng gia sư', en: 'Teacher ranking' },
  'nav.history': { vi: 'Lịch sử', en: 'History' },
  'nav.booking_requests': { vi: 'Yêu cầu lớp', en: 'Requests' },
  'nav.contract': { vi: 'Hợp đồng', en: 'Contract' },
  'nav.availability': { vi: 'Lịch rảnh', en: 'Availability' },
  'nav.schedules': { vi: 'Lịch dạy của tôi', en: 'My Schedules' },
  'nav.profile': { vi: 'Hồ sơ', en: 'Profile' },
  'nav.teacher': { vi: 'Gia sư', en: 'Teacher' },
  'nav.evaluations': { vi: 'Đánh giá', en: 'Evaluations' },
  'nav.signout': { vi: 'Đăng xuất', en: 'Sign out' },
  'nav.signed_out': { vi: 'Đã đăng xuất', en: 'Signed out' },

  // AttendancePage
  'attendance.title': { vi: 'Điểm danh', en: 'Attendance' },
  'attendance.subtitle': { vi: 'Nhập mã học viên để bắt đầu', en: 'Enter student code to start' },
  'attendance.student_code': { vi: 'Mã học viên', en: 'Student code' },
  'attendance.search': { vi: 'Tìm', en: 'Search' },
  'attendance.not_found': { vi: 'Không tìm thấy mã này', en: 'Student code not found' },
  'attendance.student_info': { vi: 'Thông tin học viên', en: 'Student info' },
  'attendance.remaining': { vi: 'buổi còn lại', en: 'sessions left' },
  'attendance.no_sessions': { vi: 'Học viên đã hết buổi học', en: 'No remaining sessions' },
  'attendance.exhausted_title': { vi: 'Học viên đã hết buổi', en: 'Student has no sessions left' },
  'attendance.exhausted_subtitle': { vi: 'Buổi học này sẽ được ghi nhận là nợ buổi.', en: 'This lesson will be recorded as a debt session.' },
  'attendance.date': { vi: 'Ngày', en: 'Date' },
  'attendance.duration': { vi: 'Thời lượng', en: 'Duration' },
  'attendance.minutes': { vi: 'phút', en: 'min' },
  'attendance.status': { vi: 'Tình trạng', en: 'Status' },
  'attendance.present': { vi: 'Có mặt', en: 'Present' },
  'attendance.excused': { vi: 'Vắng có phép', en: 'Absent with permission' },
  'attendance.unexcused': { vi: 'Vắng không phép', en: 'Absent without permission' },
  'attendance.excused_info': { vi: '✓ Vắng có phép: không cộng giờ', en: '✓ Excused absence: no minutes added' },
  'attendance.unexcused_info': { vi: '✓ Vắng không phép: cộng 25 phút mặc định', en: '✓ Unexcused absence: default 25 minutes added' },
  'attendance.comment': { vi: 'Nhận xét cho phụ huynh', en: 'Comment for parents' },
  'attendance.comment_placeholder': { vi: 'Bé học tốt, cần ôn thêm phần...', en: 'Student did well, needs to review...' },
  'attendance.homework': { vi: 'Bài tập về nhà', en: 'Homework' },
  'attendance.homework_placeholder': { vi: 'Làm bài tập 1-5 trang 20', en: 'Do exercises 1-5 page 20' },
  'attendance.images': { vi: 'Hình ảnh (tối đa 20)', en: 'Images (max 20)' },
  'attendance.add_images': { vi: 'Thêm ảnh', en: 'Add images' },
  'attendance.max_images': { vi: 'Tối đa 20 ảnh', en: 'Max 20 images' },
  'attendance.submit': { vi: 'Gửi điểm danh', en: 'Submit attendance' },
  'attendance.submitting': { vi: 'Đang gửi...', en: 'Submitting...' },
  'attendance.submitted': { vi: 'Đã gửi điểm danh!', en: 'Attendance submitted!' },
  'attendance.wait_admin': { vi: 'Chờ admin duyệt...', en: 'Waiting for admin approval...' },
  'attendance.submit_success': { vi: 'Đã gửi điểm danh, chờ admin duyệt', en: 'Attendance submitted, awaiting admin approval' },
  'attendance.subject': { vi: 'Môn học', en: 'Subject' },
  'attendance.submit_fail': { vi: 'Gửi điểm danh thất bại', en: 'Failed to submit attendance' },
  'attendance.uploading': { vi: 'Ảnh đang tải lên — vui lòng chờ hoặc bấm X gỡ ảnh đang tải rồi gửi lại', en: 'Images are still uploading — please wait or remove the uploading image, then submit again' },
  'attendance.teacher_info': { vi: 'Gia sư', en: 'Teacher' },
  'attendance.level': { vi: 'Cấp', en: 'Level' },
  'attendance.book_label': { vi: 'Tên sách (Bắt buộc)', en: 'Book/Material Name (Required)' },
  'attendance.book_placeholder': { vi: 'VD: Family and Friends 2', en: 'E.g., Family and Friends 2' },
  'attendance.book_hint': { vi: 'Chỉ viết tên sách, tối đa 20 từ (Không gửi link Drive/tài liệu)', en: 'Only write the book name, maximum 20 words (No Drive links or documents)' },

  // Structured lesson report (new attendance form)
  'report.pages_label': { vi: 'Trang học (Bắt buộc)', en: 'Pages Covered (Required)' },
  'report.pages_placeholder': { vi: 'VD: Student Book trang 18–21, Workbook trang 12–13', en: 'E.g., Student Book pages 18–21, Workbook pages 12–13' },
  'report.pages_hint': { vi: 'Chỉ viết trang học, tối đa 20 từ', en: 'Only write the pages covered, maximum 20 words' },
  'report.knowledge_label': { vi: 'Điểm kiến thức (Bắt buộc)', en: 'Knowledge Point (Required)' },
  'report.knowledge_check': { vi: 'Đã hoàn thành 1 điểm kiến thức', en: 'Completed 1 knowledge point' },
  'report.knowledge_placeholder': { vi: 'VD: Hôm nay học viên học chủ đề Colors gồm các từ vựng: red, blue, green… Học viên luyện mẫu câu "What color is it?" – "It is blue.", phát âm khá tốt và ghi nhớ được hầu hết từ vựng.', en: 'E.g., Today the student learned the Colors topic: red, blue, green… Practiced "What color is it?" – "It is blue.", pronounced well and memorized most vocabulary.' },
  'report.games_label': { vi: 'Trò chơi (Bắt buộc)', en: 'Games (Required)' },
  'report.games_check': { vi: 'Đã tổ chức 2 trò chơi', en: 'Organized 2 games' },
  'report.games_placeholder': { vi: 'VD: Học viên tham gia Wheel Spin và Guess the Picture. Hoàn thành tốt các thử thách, đạt 8/10 và 9/10 câu đúng. Tích cực tham gia và phản xạ nhanh trong quá trình chơi.', en: 'E.g., The student played Wheel Spin and Guess the Picture, scoring 8/10 and 9/10. Participated actively with quick reflexes.' },
  'report.exercises_label': { vi: 'Bài tập trên lớp (Bắt buộc)', en: 'In-class Exercises (Required)' },
  'report.exercises_check': { vi: 'Đã hoàn thành 3 bài tập', en: 'Completed 3 exercises' },
  'report.exercises_placeholder': { vi: 'VD: Học viên hoàn thành đầy đủ 3 bài tập gồm Match, Fill in the Blank và Speaking Practice. Có thể tự làm phần lớn bài tập, gia sư đã hỗ trợ sửa lỗi phát âm và ngữ pháp khi cần.', en: 'E.g., The student completed all 3 exercises: Match, Fill in the Blank and Speaking Practice, mostly independently with some pronunciation and grammar support.' },
  'report.section_comment': { vi: 'Nhận xét', en: 'Comment' },
  'report.homework_label': { vi: 'Bài tập về nhà (Bắt buộc)', en: 'Homework (Required)' },
  'report.homework_content': { vi: 'Nội dung giao cho học viên', en: 'Content assigned to the student' },
  'report.homework_hint': { vi: 'Giáo viên chọn tối đa 2 loại bài tập và điền nội dung chi tiết cho học viên.', en: 'Choose up to 2 homework types and write the details for the student.' },
  'report.homework_limit': { vi: 'Chọn tối đa 2 loại bài tập.', en: 'Choose up to 2 homework types.' },
  'report.homework_selected': { vi: 'Đã chọn', en: 'Selected' },
  'report.hw_video': { vi: 'Quay video', en: 'Record a video' },
  'report.hw_video_placeholder': { vi: 'Ví dụ: Đọc đoạn hội thoại trang 15 hoặc giới thiệu về gia đình trong 1 phút.', en: 'E.g., Read the dialogue on page 15 or introduce your family in 1 minute.' },
  'report.hw_writing': { vi: 'Bài viết', en: 'Writing' },
  'report.hw_writing_placeholder': { vi: 'Ví dụ: Viết 5 câu sử dụng cấu trúc "There is/There are" hoặc viết đoạn văn 50–70 từ về cuối tuần.', en: 'E.g., Write 5 sentences using "There is/There are" or a 50–70 word paragraph about your weekend.' },
  'report.hw_reading': { vi: 'Đọc bài', en: 'Reading' },
  'report.hw_reading_placeholder': { vi: 'Ví dụ: Đọc to bài khoá trang 20 ba lần và gạch chân từ mới chưa hiểu.', en: 'E.g., Read the passage on page 20 aloud three times and underline new words.' },
  'report.hw_listening': { vi: 'Nghe & luyện phát âm', en: 'Listening & pronunciation' },
  'report.hw_listening_placeholder': { vi: 'Ví dụ: Nghe track 12 và nhắc lại theo băng, chú ý âm cuối /s/ và /z/.', en: 'E.g., Listen to track 12 and repeat, focusing on the final /s/ and /z/ sounds.' },
  'report.hw_vocabulary': { vi: 'Ôn tập từ vựng / Workbook', en: 'Vocabulary / Workbook review' },
  'report.hw_vocabulary_placeholder': { vi: 'Ví dụ: Hoàn thành Workbook trang 12–13 (bài 1–3) và ôn lại 8 từ vựng đã học.', en: 'E.g., Complete Workbook pages 12–13 (ex. 1–3) and review the 8 vocabulary words.' },
  'report.rating_label': { vi: 'Chấm điểm buổi học', en: 'Rate the lesson' },
  'report.rating_hint': { vi: '(Chọn 4 hoặc 5 sao)', en: '(Choose 4 or 5 stars)' },
  'report.err_pages_required': { vi: 'Vui lòng nhập trang học', en: 'Please enter the pages covered' },
  'report.err_pages_words': { vi: 'Trang học không được quá 20 từ', en: 'Pages covered must not exceed 20 words' },
  'report.err_pages_link': { vi: 'Chỉ nhập trang học, không gửi link/liên kết', en: 'Enter only the pages covered, do not send links' },
  'report.err_knowledge': { vi: 'Vui lòng nhập nhận xét mục Điểm kiến thức', en: 'Please enter a comment for Knowledge Point' },
  'report.err_games': { vi: 'Vui lòng nhập nhận xét mục Trò chơi', en: 'Please enter a comment for Games' },
  'report.err_exercises': { vi: 'Vui lòng nhập nhận xét mục Bài tập trên lớp', en: 'Please enter a comment for In-class Exercises' },
  'report.err_too_short': { vi: 'Nhận xét quá ngắn — vui lòng viết tối thiểu 120 ký tự cho 3 mục để phụ huynh nắm được buổi học', en: 'Feedback is too short — please write at least 120 characters across the 3 sections' },
  'report.err_homework': { vi: 'Vui lòng chọn ít nhất 1 loại Bài tập về nhà và nhập nội dung giao', en: 'Please choose at least 1 homework type and enter its content' },
  'report.err_homework_max': { vi: 'Chỉ được chọn tối đa 2 loại bài tập về nhà', en: 'You can choose at most 2 homework types' },
  'report.err_homework_long': { vi: 'Nội dung mỗi loại bài tập không được quá 500 ký tự', en: 'Each homework type must not exceed 500 characters' },
  'report.err_rating': { vi: 'Vui lòng chấm điểm buổi học (4 hoặc 5 sao)', en: 'Please rate the lesson (4 or 5 stars)' },

  // Buổi VẮNG KHÔNG PHÉP: bắt buộc dặn dò + giao bài tập + ảnh minh chứng
  'absence.title': { vi: 'Bắt buộc trước khi gửi buổi vắng không phép', en: 'Required before submitting an unexcused absence' },
  'absence.subtitle': { vi: 'Buổi vắng không phép vẫn được tính 25 phút, nên gia sư phải để lại dặn dò, giao bài tập và tải ít nhất 1 ảnh minh chứng thì mới gửi được điểm danh.', en: 'An unexcused absence is still paid as 25 minutes, so you must leave advice, assign homework and upload at least 1 proof image before submitting.' },
  'absence.step_advice': { vi: 'Dặn dò', en: 'Advice' },
  'absence.step_homework': { vi: 'Bài tập', en: 'Homework' },
  'absence.step_image': { vi: 'Hình ảnh', en: 'Image' },
  'absence.advice_label': { vi: 'Dặn dò cho học viên & phụ huynh', en: 'Advice for the student & parents' },
  'absence.advice_placeholder': { vi: 'VD: Gia sư đã chờ hết 15 phút nhưng con không vào lớp. Nhờ phụ huynh nhắc con vào đúng giờ buổi sau, ôn lại Unit 3 và làm bài tập gia sư giao bên dưới trước buổi kế tiếp.', en: 'E.g., I waited 15 minutes but the student did not join. Please remind them to be on time next session, review Unit 3 and complete the homework assigned below.' },
  'absence.advice_ok': { vi: '✓ Dặn dò đã đủ chi tiết ({n} ký tự)', en: '✓ Advice is detailed enough ({n} characters)' },
  'absence.advice_need': { vi: 'Dặn dò còn quá ngắn: {n}/{min} ký tự — hãy nêu rõ lý do vắng và việc học viên cần làm trước buổi sau', en: 'Advice is too short: {n}/{min} characters — state what happened and what the student must do before the next session' },
  'absence.homework_label': { vi: 'Bài tập giao cho buổi vắng (Bắt buộc)', en: 'Homework for the missed session (Required)' },
  'absence.homework_hint': { vi: 'Chọn tối đa 2 loại bài tập và ghi rõ nội dung để học viên làm bù buổi vắng.', en: 'Choose up to 2 homework types and describe what the student must do to make up for the missed session.' },
  'absence.image_ok': { vi: '✓ Đã có {n} ảnh minh chứng', en: '✓ {n} proof image(s) attached' },
  'absence.image_need': { vi: 'Chưa có ảnh minh chứng — tải ít nhất 1 ảnh (bài tập đã giao hoặc màn hình lớp chờ học viên) ở mục Hình ảnh bên dưới', en: 'No proof image yet — upload at least 1 image (the assigned homework or the empty classroom screen) in the Images section below' },
  'absence.err_advice_required': { vi: 'Học viên vắng không phép: vui lòng nhập phần dặn dò trước khi gửi', en: 'Unexcused absence: please write the advice before submitting' },
  'absence.err_advice_short': { vi: 'Phần dặn dò quá ngắn — vui lòng viết tối thiểu 50 ký tự để phụ huynh nắm được tình hình', en: 'The advice is too short — please write at least 50 characters' },
  'absence.err_advice_long': { vi: 'Phần dặn dò không được quá 1000 ký tự', en: 'The advice must not exceed 1000 characters' },
  'absence.err_homework': { vi: 'Học viên vắng không phép: vui lòng chọn ít nhất 1 loại bài tập và nhập nội dung giao', en: 'Unexcused absence: please choose at least 1 homework type and enter its content' },
  'absence.err_image': { vi: 'Học viên vắng không phép: vui lòng tải lên ít nhất 1 ảnh minh chứng', en: 'Unexcused absence: please upload at least 1 proof image' },

  // LessonHistoryPage
  'history.title': { vi: 'Lịch sử buổi dạy', en: 'Lesson history' },
  'history.lessons_taught': { vi: 'Buổi đã dạy', en: 'Lessons taught' },
  'history.total_minutes': { vi: 'Tổng phút', en: 'Total min' },
  'history.monthly_salary': { vi: 'Lương tháng này', en: 'Monthly salary' },
  'history.adjustments': { vi: 'Thưởng & khấu trừ tháng này', en: 'Bonuses & deductions this month' },
  'history.adjustments_hint': { vi: 'Các khoản này đã được tính vào Lương tháng này.', en: 'These are already included in this month\'s salary.' },
  'history.bonus': { vi: 'Thưởng', en: 'Bonus' },
  'history.deduction': { vi: 'Khấu trừ', en: 'Deduction' },
  'history.no_lessons': { vi: 'Không có buổi dạy nào', en: 'No lessons found' },
  'history.month_no_lessons': { vi: 'chưa có buổi dạy nào', en: 'has no lessons yet' },
  'history.pending': { vi: 'Chờ duyệt', en: 'Pending' },
  'history.comment': { vi: 'Nhận xét', en: 'Comment' },
  'history.homework': { vi: 'Bài tập', en: 'Homework' },
  'history.month_label': { vi: 'Tháng', en: 'Month' },

  // ProfilePage
  'profile.not_found': { vi: 'Không tìm thấy hồ sơ', en: 'Profile not found' },
  'profile.level': { vi: 'Cấp', en: 'Level' },
  'profile.copy_link': { vi: 'Sao chép link hồ sơ', en: 'Copy profile link' },
  'profile.copied': { vi: 'Đã sao chép link hồ sơ', en: 'Profile link copied' },
  'profile.this_month': { vi: 'Thống kê tháng này', en: 'This month stats' },
  'profile.lessons_taught': { vi: 'Buổi đã dạy', en: 'Lessons taught' },
  'profile.income': { vi: 'Thu nhập', en: 'Income' },
  'profile.username': { vi: 'Tên đăng nhập', en: 'Username' },
  'profile.need_help': { vi: 'Cần hỗ trợ từ Admin?', en: 'Need help from Admin?' },
  'profile.contact_admin': { vi: 'Mọi thay đổi về thông tin cá nhân vui lòng liên hệ Admin qua Zalo hoặc Hotline để được cập nhật.', en: 'For any profile changes, please contact Admin via Zalo or Hotline.' },
  'profile.approved': { vi: 'Đã duyệt', en: 'Approved' },
  'profile.rejected': { vi: 'Từ chối', en: 'Rejected' },
  'profile.pending': { vi: 'Chờ duyệt', en: 'Pending' },
  'profile.delete_cert': { vi: 'Xóa bằng cấp', en: 'Delete certificate' },
  'profile.cert_category': { vi: 'Loại bằng cấp *', en: 'Category *' },
  'profile.cert_lang': { vi: 'Năng lực chuyên môn (IELTS/TOEIC...)', en: 'Professional competency (IELTS/TOEIC...)' },
  'profile.cert_pedagogical': { vi: 'Nghiệp vụ sư phạm', en: 'Pedagogical Certificate' },
  'profile.cert_other': { vi: 'Khác', en: 'Other' },
  'profile.cert_status': { vi: 'Trạng thái duyệt', en: 'Approval Status' },
  'profile.cert_title': { vi: 'Tên bằng / Chứng chỉ *', en: 'Certificate Title *' },
  'profile.cert_score': { vi: 'Điểm số / Xếp loại *', en: 'Score / Grade *' },
  'profile.view_image': { vi: 'Xem ảnh bằng', en: 'View Image' },
  'profile.delete_image': { vi: 'Xóa ảnh', en: 'Delete Image' },
  'profile.upload_image': { vi: 'Tải ảnh lên (Image only)', en: 'Upload Image (Image only)' },

  // ContractPage
  'contract.title': { vi: 'Hợp đồng & Điều khoản', en: 'Contract & Terms' },
  'contract.status': { vi: 'Trạng thái', en: 'Status' },
  'contract.agreed': { vi: 'Đã đồng ý', en: 'Agreed' },
  'contract.not_agreed': { vi: 'Chưa đồng ý', en: 'Not agreed' },
  'contract.agree_btn': { vi: 'Tôi đồng ý với Điều khoản sử dụng', en: 'I agree to the Terms of Service' },
  'contract.confirm': { vi: 'Xác nhận đồng ý', en: 'Confirm agreement' },
  'contract.scroll_hint': { vi: 'Vui lòng cuộn đọc hết điều khoản để tiếp tục', en: 'Please scroll to read all terms to continue' },
  'contract.agreed_at': { vi: 'Đã đồng ý lúc', en: 'Agreed at' },
  'contract.ip': { vi: 'Địa chỉ IP', en: 'IP address' },
  'contract.device': { vi: 'Thiết bị', en: 'Device' },
  'contract.version': { vi: 'Phiên bản', en: 'Version' },

  // Availability
  'avail.title': { vi: 'Lịch rảnh của bạn', en: 'Your Availability' },
  'avail.subtitle': { vi: 'Đăng ký lịch rảnh hàng tuần để Admin sắp lịch dạy phù hợp', en: 'Register your weekly availability so Admin can schedule classes accordingly' },
  'avail.available': { vi: 'Rảnh', en: 'Available' },
  'avail.unavailable': { vi: 'Bận', en: 'Busy' },
  'avail.add_time': { vi: '+ Thêm khung giờ', en: '+ Add time slot' },
  'avail.remove_time': { vi: 'Xóa', en: 'Remove' },
  'avail.note': { vi: 'Ghi chú', en: 'Note' },
  'avail.note_placeholder': { vi: 'VD: Tháng 6 bận thi, nghỉ 2 tuần...', en: 'E.g., June is busy with exams, off for 2 weeks...' },
  'avail.save': { vi: 'Lưu lịch rảnh', en: 'Save availability' },
  'avail.saving': { vi: 'Đang lưu...', en: 'Saving...' },
  'avail.saved': { vi: 'Đã lưu lịch rảnh!', en: 'Availability saved!' },
  'avail.save_fail': { vi: 'Lưu thất bại', en: 'Failed to save' },
  'avail.last_updated': { vi: 'Đã lưu lúc', en: 'Last saved at' },
  'avail.not_set': { vi: 'Chưa cập nhật', en: 'Not set' },
  'avail.mon': { vi: 'Thứ 2', en: 'Mon' },
  'avail.tue': { vi: 'Thứ 3', en: 'Tue' },
  'avail.wed': { vi: 'Thứ 4', en: 'Wed' },
  'avail.thu': { vi: 'Thứ 5', en: 'Thu' },
  'avail.fri': { vi: 'Thứ 6', en: 'Fri' },
  'avail.sat': { vi: 'Thứ 7', en: 'Sat' },
  'avail.sun': { vi: 'CN', en: 'Sun' },
  'avail.start': { vi: 'Từ', en: 'From' },
  'avail.end': { vi: 'Đến', en: 'To' },
  'avail.announcement_title': { vi: 'THÔNG BÁO', en: 'ANNOUNCEMENT' },
  'avail.announcement_p1': { vi: 'Hiện tại một số gia sư tạm thời không thể điểm danh do chưa cập nhật lịch rảnh trên Platform.', en: 'Currently, some teachers are temporarily unable to take attendance because they have not updated their availability on the Platform.' },
  'avail.announcement_p2': { vi: 'Gia sư vui lòng cập nhật lịch rảnh. Sau khi cập nhật thành công, hệ thống sẽ tự động mở lại quyền điểm danh.', en: 'Please update your availability. After a successful update, the system will automatically restore your attendance privileges.' },
  'avail.announcement_p3': { vi: 'Xin cảm ơn các thầy cô đã phối hợp!', en: 'Thank you for your cooperation!' },
  'avail.understand': { vi: 'Đã hiểu', en: 'Understood' },
  'avail.setup_required_title': { vi: 'Yêu cầu thiết lập lịch trống ban đầu', en: 'Initial Schedule Setup Required' },
  'avail.setup_required_desc': { vi: 'Bạn đang được chuyển hướng đến đây vì tài khoản chưa có lịch trống rảnh dạy. Vui lòng chọn các khung giờ rảnh của bạn trên bảng và nhấn "Lưu lịch dạy trống tương lai" ở cuối trang để hoàn tất thiết lập tài khoản và mở khóa các tính năng khác (như Điểm danh, Lịch dạy).', en: 'You have been redirected here because your account has no scheduled availability. Please select your free time slots on the board and click "Save Future Availability" at the bottom of the page to complete your account setup and unlock other features (such as Attendance, Teaching Schedule).' },
  'avail.prev_week': { vi: 'Tuần trước', en: 'Previous week' },
  'avail.current_week': { vi: 'Tuần này', en: 'This week' },
  'avail.next_week': { vi: 'Tuần sau', en: 'Next week' },
  'avail.view': { vi: 'Xem', en: 'View' },
  'avail.25_min': { vi: '25 phút', en: '25 mins' },
  'avail.50_min': { vi: '50 phút', en: '50 mins' },
  'avail.warning_title': { vi: 'Cân nhắc kỹ lịch dạy trống trước khi lưu!', en: 'Consider your availability carefully before saving!' },
  'avail.warning_desc': { vi: 'Các khung giờ lịch dạy rảnh sau khi bấm lưu sẽ không thể tự chỉnh sửa hoặc hủy/xóa được. Muốn thay đổi, bạn phải liên hệ với quản lý. Hãy cân nhắc lịch!', en: 'Free time slots cannot be manually edited, cancelled, or deleted after saving. If you need to make changes, please contact the manager. Please consider your schedule carefully!' },
  'avail.booked': { vi: 'ĐÃ XẾP LỚP', en: 'BOOKED' },
  'avail.save_future': { vi: 'Lưu lịch dạy trống tương lai', en: 'Save Future Availability' },
  'avail.confirm_title': { vi: 'Xác nhận lưu lịch dạy tương lai', en: 'Confirm Future Schedule Save' },
  'avail.confirm_cancel': { vi: 'Hủy', en: 'Cancel' },
  'avail.confirm_ok': { vi: 'Tôi đã cân nhắc lịch và đồng ý', en: 'I have considered my schedule and agree' },
  'avail.success': { vi: 'Đăng ký thành công', en: 'Availability saved successfully' },
  'avail.confirm_body_title': { vi: 'Xác nhận lưu lịch dạy?', en: 'Confirm saving schedule?' },
  'avail.confirm_body_desc': { vi: 'Lịch này sau khi lưu sẽ được áp dụng cho tuần đã chọn và tất cả các tuần trong tương lai. Các khung giờ rảnh sau khi lưu sẽ không thể tự chỉnh sửa hoặc tự xóa được. Muốn thay đổi, bạn phải liên hệ với quản lý.', en: 'Once saved, this availability will be applied to the selected week and all future weeks. Free time slots cannot be manually edited or deleted after saving. If you need to make changes, please contact the manager.' },

  // Teacher Detail (Admin)
  'td.title': { vi: 'Chi tiết gia sư', en: 'Teacher Detail' },
  'td.not_found': { vi: 'Không tìm thấy gia sư', en: 'Teacher not found' },
  'td.edit': { vi: 'Sửa', en: 'Edit' },
  'td.subjects': { vi: 'Môn dạy', en: 'Subjects' },
  'td.level': { vi: 'Level', en: 'Level' },
  'td.bio': { vi: 'Giới thiệu', en: 'Bio' },
  'td.stats_lessons': { vi: 'Buổi đã dạy', en: 'Lessons taught' },
  'td.stats_minutes': { vi: 'Tổng phút', en: 'Total minutes' },
  'td.stats_salary': { vi: 'Tổng lương', en: 'Total salary' },
  'td.availability': { vi: 'Lịch rảnh', en: 'Availability' },
  'td.classes': { vi: 'Lớp đang dạy', en: 'Active classes' },
  'td.history': { vi: 'Lịch sử buổi dạy', en: 'Lesson history' },
  'td.student': { vi: 'Học viên', en: 'Student' },
  'td.student_code': { vi: 'Mã HV', en: 'Code' },
  'td.total_sessions': { vi: 'Tổng buổi', en: 'Total' },
  'td.used_sessions': { vi: 'Đã học', en: 'Used' },
  'td.remaining': { vi: 'Còn lại', en: 'Left' },
  'td.date': { vi: 'Ngày', en: 'Date' },
  'td.minutes': { vi: 'Phút', en: 'Min' },
  'td.status': { vi: 'Trạng thái', en: 'Status' },
  'td.no_classes': { vi: 'Chưa có lớp nào', en: 'No classes yet' },
  'td.no_lessons': { vi: 'Chưa có buổi dạy nào', en: 'No lessons yet' },

  // Login Page
  'login.subtitle': { vi: 'Nền tảng quản lý #1 cho Gia sư', en: '#1 Management Platform for Tutors' },
  'login.title_part1': { vi: 'Nâng tầm', en: 'Elevate' },
  'login.title_part2': { vi: 'chất lượng giáo dục', en: 'education quality' },
  'login.desc': { vi: 'Theo dõi tiến độ, nhận bài tập & nhận xét từ gia sư — tất cả trong một nền tảng.', en: 'Track progress, get homework & teacher feedback — all in one platform.' },
  'login.trust1': { vi: 'Gia sư chất lượng', en: 'Quality Tutors' },
  'login.trust2': { vi: 'Phụ huynh tin tưởng', en: 'Trusted by Parents' },
  'login.trust3': { vi: 'Chương trình chuẩn', en: 'Standard Curriculum' },
  'login.parent_title': { vi: 'Phụ huynh & Học sinh', en: 'Parents & Students' },
  'login.parent_desc': { vi: 'Xem bài tập, nhận xét & tiến độ học tập', en: 'View homework, feedback & progress' },
  'login.login_title': { vi: 'Đăng Nhập', en: 'Login' },
  'login.login_subtitle': { vi: 'Dành cho Gia sư & Quản trị viên', en: 'For Teachers & Admins' },
  'login.username': { vi: 'Tài khoản', en: 'Username' },
  'login.username_ph': { vi: 'Ví dụ: nguyenvana', en: 'E.g. nguyenvana' },
  'login.password': { vi: 'Mật khẩu', en: 'Password' },
  'login.password_ph': { vi: 'Nhập mật khẩu', en: 'Enter password' },
  'login.btn_login': { vi: 'ĐĂNG NHẬP', en: 'LOGIN' },
  'login.footer': { vi: 'Tài khoản được cấp bởi Quản trị viên', en: 'Account provided by Administrator' },
  'login.err_incorrect': { vi: 'Tài khoản hoặc mật khẩu không đúng', en: 'Incorrect username or password' },
  'login.err_too_many': { vi: 'Quá nhiều lần thử. Vui lòng thử lại sau.', en: 'Too many attempts. Please try again later.' },
  'login.err_failed': { vi: 'Đăng nhập thất bại. Vui lòng thử lại.', en: 'Login failed. Please try again.' },
  'login.err_no_access': { vi: 'Tài khoản không có quyền truy cập', en: 'Account does not have access' },

  // WaitingApprovalPage
  'waiting.title': { vi: 'Đăng ký thành công! 🎉', en: 'Registration successful! 🎉' },
  'waiting.desc1': { vi: 'Tài khoản của bạn đang chờ Admin phê duyệt.', en: 'Your account is pending Admin approval.' },
  'waiting.desc2': { vi: 'Vui lòng liên hệ người phụ trách để được hỗ trợ nhanh nhất.', en: 'Please contact the person in charge for prompt support.' },
  'waiting.guide_title': { vi: 'Hướng dẫn nhanh', en: 'Quick Guide' },
  'waiting.step1': { vi: 'Liên hệ quản trị viên qua số điện thoại hoặc Zalo bên dưới', en: 'Contact admin via phone or Zalo below' },
  'waiting.step2': { vi: 'Thông báo tên tài khoản bạn vừa đăng ký', en: 'Provide the username you just registered' },
  'waiting.step3': { vi: 'Admin sẽ duyệt và bạn có thể đăng nhập sử dụng ngay', en: 'Admin will approve and you can log in immediately' },
  'waiting.call': { vi: 'Gọi ngay: 090.696.6691', en: 'Call now: 090.696.6691' },
  'waiting.logout': { vi: 'Đăng xuất', en: 'Sign out' },
  'waiting.check_again': { vi: 'Kiểm tra lại', en: 'Check again' },
  'waiting.account': { vi: 'Tài khoản', en: 'Account' },

  // Schedules (Teacher / Admin calendar)
  'sched.title': { vi: 'Lịch dạy của tôi', en: 'My Schedules' },
  'sched.subtitle': { vi: 'Bảng theo dõi ca học, mở rộng chi tiết phòng học và điểm danh nhanh chóng.', en: 'Track sessions, view classroom details, and check attendance quickly.' },
  'sched.loading': { vi: 'Đang tải lịch biểu dạy...', en: 'Loading teaching schedule...' },
  'sched.shift': { vi: 'Ca', en: 'Shift' },
  'sched.prev_week': { vi: 'Tuần trước', en: 'Prev Week' },
  'sched.this_week': { vi: 'Tuần này', en: 'This Week' },
  'sched.next_week': { vi: 'Tuần sau', en: 'Next Week' },
  'sched.info': { vi: 'Thông tin lớp học', en: 'Classroom Information' },
  'sched.class_slot': { vi: 'CA HỌC', en: 'CLASS SESSION' },
  'sched.student_subject': { vi: 'HỌC SINH & MÔN HỌC', en: 'STUDENT & SUBJECT' },
  'sched.subject': { vi: 'Môn học:', en: 'Subject:' },
  'sched.attendance': { vi: 'Điểm danh:', en: 'Attendance:' },
  'sched.not_checked': { vi: 'Chưa điểm danh', en: 'Unchecked' },
  'sched.completed': { vi: 'Đã hoàn thành', en: 'Completed' },
  'sched.online_class': { vi: 'Phòng học trực tuyến:', en: 'Online classroom:' },
  'sched.open_class': { vi: 'Mở lớp học', en: 'Open Class' },
  'sched.curriculum': { vi: 'Giáo trình môn học:', en: 'Curriculum:' },
  'sched.view_curriculum': { vi: 'Xem giáo trình', en: 'View Curriculum' },
  'sched.timetable_note': { vi: 'Note timetable học viên:', en: 'Student timetable note:' },
  'sched.attendance_btn': { vi: 'Điểm danh ngay', en: 'Check Attendance' },
  'sched.close': { vi: 'Đóng', en: 'Close' },
  'sched.cancel': { vi: 'Hủy', en: 'Cancel' },

  // Attendance Modal specifics
  'sched.attendance_for': { vi: 'Điểm danh:', en: 'Attendance:' },
  'sched.duration': { vi: 'Thời lượng:', en: 'Duration:' },
  'sched.status_label': { vi: 'Trạng thái điểm danh *', en: 'Attendance status *' },
  'sched.status_present': { vi: 'Đi học đủ', en: 'Present' },
  'sched.status_excused': { vi: 'Vắng có phép (0p)', en: 'Absent with permission (0p)' },
  'sched.status_unexcused': { vi: 'Vắng không phép (25p)', en: 'Absent without permission (25p)' },
  'sched.book_label': { vi: 'Sách học / Giáo trình / Tài liệu *', en: 'Book / Materials / Curriculum *' },
  'sched.book_ph': { vi: 'VD: Let\'s Go 1 - Unit 2 Lesson 1 (Tối đa 20 từ)', en: 'E.g., Let\'s Go 1 - Unit 2 Lesson 1 (Max 20 words)' },
  'sched.comment_ph': { vi: 'Nhận xét tinh thần, sự tập trung và mức độ hiểu bài của học viên...', en: 'Review concentration, attitude, and comprehension of the student...' },
  'sched.homework_ph': { vi: 'Nhiệm vụ về nhà cho học viên...', en: 'Homework assignment for the student...' },
  'sched.proof_images': { vi: 'Hình ảnh minh chứng lớp học', en: 'Classroom proof images' },
  'sched.upload_image': { vi: 'Tải ảnh', en: 'Upload' },
  'sched.proof_desc': { vi: 'Chụp màn hình buổi học trực tuyến hoặc bảng viết (tối đa 20 ảnh).', en: 'Screenshot of the online class or blackboard (max 20 images).' },

  // Parent Dashboard
  'parent.logout_title': { vi: 'Đăng xuất', en: 'Sign out' },
  'parent.join_class_now': { vi: 'Vào học ngay', en: 'Join Class Now' },
  'parent.textbook_card_title': { vi: 'Giáo trình / Sách học viên', en: 'Curriculum / Student Textbook' },
  'parent.textbook_card_desc': { vi: 'Bấm vào đây để mở và xem sách học tập trực tuyến của học viên.', en: 'Click here to open and view the online textbook for the student.' },
  'parent.view_textbook_btn': { vi: 'Xem sách học', en: 'View Textbook' },
  'parent.packages_title': { vi: 'Gói học phí các môn', en: 'Tuition Packages by Subject' },
  'parent.total_minutes': { vi: 'Tổng thời gian', en: 'Total Minutes' },
  'parent.completed_minutes': { vi: 'Đã học', en: 'Completed' },
  'parent.booked_minutes': { vi: 'Đã đặt', en: 'Booked' },
  'parent.available_minutes': { vi: 'Khả dụng', en: 'Available' },
  'parent.curriculum_label': { vi: 'Giáo trình:', en: 'Curriculum:' },
  'parent.view_curriculum_btn': { vi: 'Xem giáo trình', en: 'View Curriculum' },
  'parent.timetable_note_label': { vi: 'Ghi chú lịch học:', en: 'Timetable note:' },
  'parent.stats_30days': { vi: 'Buổi 30 ngày qua', en: 'Sessions Last 30 Days' },
  'parent.avg_duration': { vi: 'Thời lượng TB', en: 'Avg Duration' },
  'parent.minutes_per_session': { vi: 'phút/buổi', en: 'min/session' },
  'parent.total_minutes_completed': { vi: 'Tổng {minutes} phút đã học', en: 'Total {minutes} min completed' },
  'parent.timetable_title': { vi: 'Thời khóa biểu tuần', en: 'Weekly Timetable' },
  'parent.this_week_btn': { vi: 'Tuần này', en: 'This Week' },
  'parent.no_classes_this_week': { vi: 'Không có lịch học trong tuần này', en: 'No classes scheduled this week' },
  'parent.timetable_week_label': { vi: 'Tuần {start} - {end}', en: 'Week of {start} - {end}' },
  'parent.modal_title': { vi: 'Chi tiết lịch học', en: 'Class Session Details' },
  'parent.modal_time': { vi: 'Thời gian học', en: 'Class Time' },
  'parent.modal_teacher': { vi: 'Gia sư', en: 'Teacher' },
  'parent.modal_subject': { vi: 'Môn học', en: 'Subject' },
  'parent.modal_classroom': { vi: 'Phòng học trực tuyến', en: 'Online Classroom' },
  'parent.modal_join': { vi: 'Vào phòng học', en: 'Join Classroom' },
  'parent.modal_timetable_note': { vi: 'Ghi chú lịch học', en: 'Timetable Note' },

  // Common
  'common.subject': { vi: 'Môn học', en: 'Subject' },

  // Landing Page
  'landing.hero_title1': { vi: 'Nâng tầm', en: 'Elevate' },
  'landing.hero_title2': { vi: 'chất lượng giáo dục', en: 'education quality' },
  'landing.hero_desc': { vi: 'Theo dõi tiến độ và nhận xét học tập dễ dàng, minh bạch.', en: 'Track learning progress and get transparent feedback easily.' },
  'landing.feat1_title': { vi: 'Theo dõi tiến độ', en: 'Track progress' },
  'landing.feat1_desc': { vi: 'Cập nhật kết quả học tập theo từng buổi học.', en: 'Get updated learning results after each session.' },
  'landing.feat2_title': { vi: 'Nhận xét chi tiết', en: 'Detailed feedback' },
  'landing.feat2_desc': { vi: 'Gia sư nhận xét, đánh giá sau mỗi buổi học.', en: 'Teachers give feedback and reviews after each session.' },
  'landing.feat3_title': { vi: 'Kết nối dễ dàng', en: 'Easy connection' },
  'landing.feat3_desc': { vi: 'Thông tin minh bạch, gắn kết gia đình và gia sư.', en: 'Transparent info connecting families and teachers.' },
  'landing.search_title': { vi: 'Tra cứu tiến độ học tập', en: 'Check learning progress' },
  'landing.search_subtitle': { vi: 'Dành cho phụ huynh / học sinh', en: 'For parents / students' },
  'landing.search_placeholder': { vi: 'Nhập mã học sinh', en: 'Enter student code' },
  'landing.search_hint': { vi: 'Mã học sinh được gia sư cung cấp', en: 'Student code is provided by the teacher' },
  'landing.search_btn': { vi: 'Xem tiến độ', en: 'View progress' },
  'landing.search_safe': { vi: 'Không cần đăng nhập. Bảo mật & an toàn thông tin.', en: 'No login required. Secure & private.' },
  'landing.login_title': { vi: 'Đăng nhập hệ thống', en: 'System login' },
  'landing.login_subtitle': { vi: 'Dành cho gia sư & admin', en: 'For teachers & admin' },
  'landing.login_teacher': { vi: 'Gia sư', en: 'Teacher' },
  'landing.login_admin': { vi: 'Admin', en: 'Admin' },
  'landing.login_note': { vi: 'Chỉ dành cho gia sư và quản trị hệ thống.', en: 'For teachers and system administrators only.' },
  'landing.nav_home': { vi: 'Trang chủ', en: 'Home' },
  'landing.nav_about': { vi: 'Giới thiệu', en: 'About' },
  'landing.nav_programs': { vi: 'Chương trình học', en: 'Programs' },
  'landing.nav_news': { vi: 'Tin tức', en: 'News' },
  'landing.nav_contact': { vi: 'Liên hệ', en: 'Contact' },
}

export const useLanguageStore = create<LangState>()(
  persist(
    (set, get) => ({
      lang: 'vi',
      setLang: (lang) => set({ lang }),
      t: (key: string) => {
        const entry = translations[key]
        if (!entry) return key
        return entry[get().lang] || entry['vi'] || key
      },
    }),
    { name: '123english-lang' }
  )
)
